version: "3.1"

services:
  gobarber_db:
    image: postgres
    container_name: gobarber_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gobarber
    ports:
      - 5432:5432

  gobarber_mongodb:
    image: mongo
    container_name: gobarber_mongodb
    ports:
      - 27017:27017

  gobarber_redis:
    image: redis:alpine
    container_name: gobarber_redis
    ports:
      - 6379:6379
